#1
library(queueing)
x<-NewInput.MMC(lambda =15/60,mu=1/3,c=1,n=0)
y<-QueueingModel(x)
summary(y)
B_erlang(c=1,u=lambda/mu)
L(y)
Report(y)
Pn(y)
print(y)
RO(y)
CheckInput(x)

#2
library(queueing)
x<-NewInput.MMC(lambda =1/30,mu=1/2.5,c=1,n=6)
y<-QueueingModel(x)
summary(y)
B_erlang(c=1,u=lambda/mu)
L(y)
Report(y)
Pn(y)
print(y)
RO(y)
CheckInput(x)

#3
library(queueing)
x<-NewInput.MMC(lambda =30/(24*60),mu=1/36,c=1,n=9)
y<-QueueingModel(x)
summary(y)
B_erlang(c=1,u=lambda/mu)
L(y)
Report(y)
Pn(y)
print(y)
RO(y)
CheckInput(x)

#4
library(queueing)
x<-NewInput.MMC(lambda =1/10,mu=1/3,c=1,n=0)
y<-QueueingModel(x)
summary(y)
B_erlang(c=1,u=lambda/mu)
L(y)
Report(y)
Pn(y)
print(y)
RO(y)
CheckInput(x)

